---

#  ____  _                     _          __  __ _ _             _
# / ___|| |__   __ _  ___   __| |_      _|  \/  (_) | ____ _  __| | ___
# \___ \| '_ \ / _` |/ _ \ / _` \ \ /\ / / |\/| | | |/ / _` |/ _` |/ _ \
#  ___) | | | | (_| | (_) | (_| |\ V  V /| |  | | |   < (_| | (_| | (_) |
# |____/|_| |_|\__,_|\___/ \__,_| \_/\_/ |_|  |_|_|_|\_\__,_|\__,_|\___/
#
#Copyright Â© 2022
# If you use this plugin please write a little credit, thx :)
# If you have any problems contact me at Discord, ØªâƒŸâƒ¤ Shadow ðŸ™ƒ | Ïˆ#0817

#Info:
# {size} to get new player scale

Change Size Message: "Â§aYour size has been multiplied by {size}" #You can put here {size}

Error Message: "Â§cInvalid syntax, please use /size <int> !"

No Permission Message: "Â§cYou don't have the right permission to use this command!"

# To reset your size, execute the command /size 1

---